server:
  port: 80

spring:
  jpa:
    hibernate.ddl-auto: update
    hibernate:
      types:
        print:
          banner: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    show-sql: true

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 0
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20